builds:
- id: "pharos"
  main: cmd/pharos/main.go
  binary: bin/pharos
- id: "pharos-api-server"
  main: cmd/pharos-api-server/main.go
  binary: bin/pharos-api-server
archives:
- id: "pharos"
  builds:
    - "pharos"
    - "pharos-api-server"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  format: zip
  files:
    - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
