project_name: pharos
builds:
- id: "pharos"
  main: ./cmd/pharos
  binary: bin/pharos
  goarch:
    - amd64
  goos:
    - linux
    - darwin
  ldflags:
    -X github.com/emilyzhang/pharos/pkg/pharos/cmd.pharosVersion={{.Version}}
archives:
- id: "pharos"
  builds:
    - "pharos"
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
