project_name: pharos
builds:
- id: "pharos"
  main: ./cmd/pharos
  binary: bin/pharos
  goarch:
    - amd64
  goos:
    - linux
    - darwin
  ldflags:
    -X github.com/emilyzhang/pharos/pkg/pharos/cmd.pharosVersion={{.Version}}
archives:
- id: "pharos"
  builds:
    - "pharos"
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - LICENSE
brews:
- name: "pharos"
  ids:
  - "pharos"
  github:
    owner: lob
    name: homebrew-internal
  folder: Formula
  homepage: "https://github.com/lob/pharos"
  description: "CLI for discovery and distribution of kubeconfig files."
  test: |
    system "#{bin}/pharos --version"
  install: |
    bin.install "pharos"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
