version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
      - image: circleci/postgres:11.3
        environment:
          POSTGRES_USER: pharos_admin
          POSTGRES_DB: pharos_test
    environment:
      - ENVIRONMENT: "test"
    working_directory: /go/src/github.com/lob/pharos
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/src/github.com/lob/pharos/.git
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Setup project
          command: make setup
      - run:
          name: Install dependencies
          command: make install
      - run:
          name: Run DB migration
          command: make migrate
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/lob/pharos/vendor
            - ~/.cache/go-build
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test
      - run:
          name: Enforce coverage
          command: make enforce
      - store_artifacts:
          path: coverage.out

experimental:
  notify:
    branches:
      only:
        - master
